import { Counter } from "./api";

export const SAMPLE_COUNTERS: Omit<Counter, "id">[] = [
  {
    name: "Autos",
    color: "green",
    count: 0,
    stepSize: 1,
    locked: false,
    icon: "car",
  },
  {
    name: "Häuser",
    color: "blue",
    count: 4,
    stepSize: 1,
    locked: false,
    icon: "house",
  },
  {
    name: "Bäume",
    color: "green",
    count: 0,
    stepSize: 1,
    locked: false,
    icon: "trees",
  },
  {
    name: "Berge",
    color: "orange",
    count: 12,
    stepSize: 1,
    locked: false,
    icon: "mountain",
  },
  {
    name: "Kameras",
    color: "purple",
    count: 0,
    stepSize: 1,
    locked: true,
    icon: "camera",
  },
  {
    name: "Bananen",
    color: "yellow",
    count: 42,
    stepSize: 1,
    locked: true,
    icon: "banana",
  },
  {
    name: "Sonnen",
    color: "red",
    count: 1,
    stepSize: 1,
    locked: false,
    icon: "sun",
  },
];
