name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        run: |
          echo "Deploying to server"

          ssh server "mkdir -p /root/projects/counter"

          echo "Copying files to server"
          rsync -avz --delete \
            --exclude '.git' \
            --exclude 'node_modules' \
            --exclude '.gitignore' \
            ./ server:/root/projects/counter/

          ssh server "cd /root/projects/counter && \
            touch .env && \
            echo 'BACKEND_URL=${{ secrets.BACKEND_URL }}' >> .env && \
            echo 'FRONTEND_URL=${{ secrets.FRONTEND_URL }}' >> .env && \
            echo 'NODE_ENV=production' >> .env && \
            echo 'POSTGRES_USER=${{ secrets.POSTGRES_USER }}' >> .env && \
            echo 'POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}' >> .env && \
            echo 'POSTGRES_DB=${{ secrets.POSTGRES_DB }}' >> .env && \
            echo 'POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}' >> .env && \
            echo 'POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}' >> .env"

          echo "Deploying services"
          ssh server "cd /root/projects/counter && docker compose up -d --build"
          echo "Deployed successfully"
